services:
  - type: web
    name: comentsia
    env: python
    buildCommand: "pip install --upgrade pip && pip install --retries 5 --timeout 60 -r requirements.txt"
    startCommand: gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false


