"""init

Revision ID: 0743cc990aee
Revises: 85c79f084391
Create Date: 2025-12-21 20:18:08.905665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0743cc990aee'
down_revision = '85c79f084391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
