"""init

Revision ID: 11bcf0a6450e
Revises: f9a5961bd5ec
Create Date: 2025-12-19 19:00:05.213127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bcf0a6450e'
down_revision = 'f9a5961bd5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relatorio_historico', sa.Column('filtro_ficha', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relatorio_historico', 'filtro_ficha')
    # ### end Alembic commands ###
