"""init

Revision ID: 1556b07bab8f
Revises: c752d9825bc5
Create Date: 2025-11-02 10:10:58.026361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1556b07bab8f'
down_revision = 'c752d9825bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('contexto_personalizado', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'contexto_personalizado')
    # ### end Alembic commands ###
