"""Adiciona campo gbp_tone e gbp_auto_enabled em UserSettings

Revision ID: 16988a807ff1
Revises: 393e11de422e
Create Date: 2025-10-05 19:50:36.719732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16988a807ff1'
down_revision = '393e11de422e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('gbp_tone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gbp_tone')
    # ### end Alembic commands ###
