"""stripe price ids fix

Revision ID: 1c74f25e7739
Revises: b7e060643960
Create Date: 2025-11-27 16:17:13.796981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c74f25e7739'
down_revision = 'b7e060643960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
