"""feat: adiciona logica de qr code nativo e redirecionamento de 5 estrelas

Revision ID: 247b78355894
Revises: 356c09e2c60f
Create Date: 2026-06-16 14:01:39.427183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247b78355894'
down_revision = '356c09e2c60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
