"""Atualiza UserSettings com campos GBP

Revision ID: 25a36cff3838
Revises: a35eb2341fc5
Create Date: 2025-10-08 11:29:12.994215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a36cff3838'
down_revision = 'a35eb2341fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
