"""altera pesquisa_configs para multiplas pesquisas

Revision ID: 2d232127f686
Revises: 753eeb832fcc
Create Date: 2026-06-14 20:09:43.769186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d232127f686'
down_revision = '753eeb832fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesquisa_respostas_pesquisa_config_id'), table_name='pesquisa_respostas')
    op.drop_table('pesquisa_respostas')
    op.drop_index(op.f('ix_pesquisa_configs_company_id'), table_name='pesquisa_configs')
    op.create_index(op.f('ix_pesquisa_configs_company_id'), 'pesquisa_configs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesquisa_configs_company_id'), table_name='pesquisa_configs')
    op.create_index(op.f('ix_pesquisa_configs_company_id'), 'pesquisa_configs', ['company_id'], unique=True)
    op.create_table('pesquisa_respostas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pesquisa_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cliente_nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cliente_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cliente_whatsapp', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status_alerta', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pesquisa_config_id'], ['pesquisa_configs.id'], name=op.f('pesquisa_respostas_pesquisa_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pesquisa_respostas_pkey'))
    )
    op.create_index(op.f('ix_pesquisa_respostas_pesquisa_config_id'), 'pesquisa_respostas', ['pesquisa_config_id'], unique=False)
    # ### end Alembic commands ###
