"""Add idioma_resposta em UserSettings

Revision ID: 2e5934d2598c
Revises: 247b78355894
Create Date: 2026-06-19 13:24:04.016745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5934d2598c'
down_revision = '247b78355894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('idioma_resposta', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'idioma_resposta')
    # ### end Alembic commands ###
