"""add upload_log_id to review

Revision ID: 393e11de422e
Revises: 23fbeb145e0b
Create Date: 2025-09-01 20:58:22.999062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393e11de422e'
down_revision = '23fbeb145e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('upload_log_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_review_upload_log_id'), 'review', ['upload_log_id'], unique=False)
    op.create_foreign_key(None, 'review', 'upload_log', ['upload_log_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_index(op.f('ix_review_upload_log_id'), table_name='review')
    op.drop_column('review', 'upload_log_id')
    # ### end Alembic commands ###
