"""Adiciona campo source em Review

Revision ID: 3cbbc6acfbc0
Revises: 57c1c13b6c7b
Create Date: 2025-08-18 14:25:11.652767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbbc6acfbc0'
down_revision = '57c1c13b6c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
