"""Altera Review.date para DateTime com timezone

Revision ID: 3ccbe3b1b60c
Revises: 6fa0612dd8c7
Create Date: 2025-07-23 15:31:53.998355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccbe3b1b60c'
down_revision = '6fa0612dd8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposta_especial_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('data_uso', sa.Date(), nullable=False),
    sa.Column('quantidade_usos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column(
            'date',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
            postgresql_using="date::timestamp with time zone"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('resposta_especial_uso')
    # ### end Alembic commands ###
