"""Adiciona logo e gerente em UserSettings

Revision ID: 408fabda8592
Revises: 40df502080bf
Create Date: 2025-07-20 19:12:12.148122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408fabda8592'
down_revision = '40df502080bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('manager_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('manager_name')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
