"""initial

Revision ID: 40df502080bf
Revises: 
Create Date: 2025-07-18 16:19:30.499073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40df502080bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo_pdf', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('arquivo_pdf')

    # ### end Alembic commands ###
