"""stripe price ids fix

Revision ID: 49f66aca9be7
Revises: 1c74f25e7739
Create Date: 2025-11-27 16:19:19.703195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f66aca9be7'
down_revision = '1c74f25e7739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
