"""Add gbp_auto_enabled to UserSettings

Revision ID: 56a7870238bb
Revises: 16988a807ff1
Create Date: 2025-10-05 21:46:52.190262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a7870238bb'
down_revision = '16988a807ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('gbp_auto_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gbp_auto_enabled')
    # ### end Alembic commands ###
