"""Migração inicial limpa

Revision ID: 57c1c13b6c7b
Revises:
Create Date: 2025-08-14 12:43:23.153838

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57c1c13b6c7b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consideracoes_uso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("data_uso", sa.Date(), nullable=False),
        sa.Column("quantidade_usos", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legal_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "relatorio_historico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("data_criacao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filtro_periodo", sa.String(length=50), nullable=True),
        sa.Column("filtro_nota", sa.String(length=50), nullable=True),
        sa.Column("filtro_respondida", sa.String(length=50), nullable=True),
        sa.Column("nome_arquivo", sa.String(length=255), nullable=True),
        sa.Column("caminho_arquivo", sa.String(length=500), nullable=True),
        sa.Column("arquivo_pdf", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resposta_especial_uso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("data_uso", sa.Date(), nullable=False),
        sa.Column("quantidade_usos", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("reviewer_name", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("replied", sa.Boolean(), nullable=True),
        sa.Column("terms_accepted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("business_name", sa.String(length=255), nullable=True),
        sa.Column("default_greeting", sa.String(length=255), nullable=True),
        sa.Column("default_closing", sa.String(length=255), nullable=True),
        sa.Column("contact_info", sa.String(length=255), nullable=True),
        sa.Column("terms_accepted", sa.Boolean(), nullable=True),
        sa.Column("logo", sa.LargeBinary(), nullable=True),
        sa.Column("manager_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_boas_vindas_enviado", sa.Boolean(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("plano", sa.String(length=32), nullable=True),
        sa.Column("plano_ate", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=True),
        sa.Column("foto_url", sa.String(length=512), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "filial_vinculo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_user_id", sa.String(), nullable=False),
        sa.Column("child_user_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data_convite", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_aceite", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_user_id", "child_user_id", name="uq_parent_child"),
    )
    with op.batch_alter_table("filial_vinculo", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_filial_vinculo_child_user_id"),
            ["child_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filial_vinculo_parent_user_id"),
            ["parent_user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filial_vinculo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filial_vinculo_parent_user_id"))
        batch_op.drop_index(batch_op.f("ix_filial_vinculo_child_user_id"))

    op.drop_table("filial_vinculo")
    op.drop_table("users")
    op.drop_table("user_settings")
    op.drop_table("review")
    op.drop_table("resposta_especial_uso")
    op.drop_table("relatorio_historico")
    op.drop_table("legal_documents")
    op.drop_table("consideracoes_uso")
    # ### end Alembic commands ###
