"""Adiciona relacionamento parent_user e child_user

Revision ID: 5d22c8582c4b
Revises: 1dc811b8c70e
Create Date: 2025-08-12 22:57:43.241672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d22c8582c4b'
down_revision = '1dc811b8c70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_filial_vinculo_child_user', 'user', ['child_user_id'], ['id'])
        batch_op.create_foreign_key('fk_filial_vinculo_parent_user', 'user', ['parent_user_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_filial_vinculo_child_user', type_='foreignkey')
        batch_op.drop_constraint('fk_filial_vinculo_parent_user', type_='foreignkey')
    # ### end Alembic commands ###
