"""init

Revision ID: 6f399cd7fc92
Revises: 0d42536fdd4d
Create Date: 2025-10-22 09:56:29.988827

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f399cd7fc92"
down_revision = "0d42536fdd4d"
branch_labels = None
depends_on = None


def upgrade():
    # adiciona como nullable primeiro
    op.add_column("review", sa.Column("is_auto", sa.Boolean(), nullable=True))
    op.add_column("review", sa.Column("auto_origin", sa.String(), nullable=True))

    # define valor padrão para registros antigos
    op.execute("UPDATE review SET is_auto = FALSE, auto_origin = NULL")

    # agora força o NOT NULL
    op.alter_column("review", "is_auto", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "auto_origin")
    op.drop_column("review", "is_auto")
    # ### end Alembic commands ###
