"""Adicionar campo email_boas_vindas_enviado em UserSettings

Revision ID: 6fa0612dd8c7
Revises: ec067b09a118
Create Date: 2025-07-21 15:30:27.195539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa0612dd8c7'
down_revision = 'ec067b09a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_boas_vindas_enviado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('email_boas_vindas_enviado')

    # ### end Alembic commands ###
