"""init

Revision ID: 74471dce2b70
Revises: c4b82f83c966
Create Date: 2025-11-23 13:36:46.634472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74471dce2b70'
down_revision = 'c4b82f83c966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('consumido', sa.Boolean(), nullable=True))
    op.drop_column('user_settings', 'consumido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('consumido', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('payment_transactions', 'consumido')
    # ### end Alembic commands ###
