"""Resetar migrações no Render

Revision ID: 750d9d162c0a
Revises: 
Create Date: 2025-07-25 14:20:26.298528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750d9d162c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta_especial_uso', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta_especial_uso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=30), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
