"""ajustes google_auto / reconciliacao

Revision ID: 753eeb832fcc
Revises: 0743cc990aee
Create Date: 2025-12-27 20:46:07.842182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753eeb832fcc'
down_revision = '0743cc990aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
