"""atualização google_auto automação diária

Revision ID: 7b096e5e8884
Revises: 6f399cd7fc92
Create Date: 2025-10-22 14:08:12.005259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b096e5e8884'
down_revision = '6f399cd7fc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
