"""Adiciona is_parent e parent_user_id

Revision ID: 7f091e6c4205
Revises: ee59ff9feda9
Create Date: 2025-12-15 19:40:00.900212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f091e6c4205'
down_revision = 'ee59ff9feda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('is_parent', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('parent_user_id', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'parent_user_id')
    op.drop_column('user_settings', 'is_parent')
    # ### end Alembic commands ###
