"""init

Revision ID: 85c79f084391
Revises: 11bcf0a6450e
Create Date: 2025-12-21 19:55:54.752025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c79f084391'
down_revision = '11bcf0a6450e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_locations', sa.Column('ast_reconcile_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_locations', 'ast_reconcile_at')
    # ### end Alembic commands ###
