"""add gbp_slots_extras

Revision ID: 8798fae46b0b
Revises: c09d9180e86b
Create Date: 2025-12-14 21:18:19.955515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8798fae46b0b'
down_revision = 'c09d9180e86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('gbp_slots_extras', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gbp_slots_extras')
    # ### end Alembic commands ###
