"""add external_id, fingerprint, source to review

Revision ID: 92c1091975c7
Revises: 3cbbc6acfbc0
Create Date: 2025-08-23 15:23:05.489144

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92c1091975c7"
down_revision = "3cbbc6acfbc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation_index",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "source",
            "external_id",
            name="uq_reservation_index_user_source_extid",
        ),
    )
    with op.batch_alter_table("reservation_index", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reservation_index_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reservation_index_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "upload_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("filesize", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inserted", sa.Integer(), nullable=True),
        sa.Column("duplicates", sa.Integer(), nullable=True),
        sa.Column("skipped", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=True),
        sa.Column("errors_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("upload_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_upload_log_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_upload_log_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("external_id", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("fingerprint", sa.String(length=128), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_review_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_fingerprint"), ["fingerprint"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_review_external_id"))
        batch_op.drop_column("fingerprint")
        batch_op.drop_column("external_id")

    with op.batch_alter_table("upload_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_upload_log_source"))

    op.drop_table("upload_log")
    with op.batch_alter_table("reservation_index", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reservation_index_user_id"))
        batch_op.drop_index(batch_op.f("ix_reservation_index_source"))

    op.drop_table("reservation_index")
    # ### end Alembic commands ###
