"""Add google_refresh_token to UserSettings

Revision ID: a35eb2341fc5
Revises: 56a7870238bb
Create Date: 2025-10-05 22:37:52.744498

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a35eb2341fc5"
down_revision = "56a7870238bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column("google_refresh_token", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "google_refresh_token")
    # ### end Alembic commands ###
