"""ajuste google_auto

Revision ID: ac05cab08990
Revises: 1556b07bab8f
Create Date: 2025-11-09 12:02:43.327261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac05cab08990'
down_revision = '1556b07bab8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
