"""Adiciona coluna idioma_resposta e corrige contextos

Revision ID: b5ad1b4fb649
Revises: 2e5934d2598c
Create Date: 2026-06-19 14:06:24.643559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ad1b4fb649'
down_revision = '2e5934d2598c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
