"""update homepage visitor layout

Revision ID: b7e060643960
Revises: 74471dce2b70
Create Date: 2025-11-23 18:22:57.398271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e060643960'
down_revision = '74471dce2b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
