"""add filial_vinculo

Revision ID: bf8ecbe16e73
Revises: 2d0c7f683875
Create Date: 2025-08-11 20:35:26.153542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8ecbe16e73'
down_revision = '2d0c7f683875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filial_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.String(), nullable=False),
    sa.Column('child_user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'child_user_id', name='uq_parent_child')
    )
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filial_vinculo_child_user_id'), ['child_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filial_vinculo_parent_user_id'), ['parent_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filial_vinculo_parent_user_id'))
        batch_op.drop_index(batch_op.f('ix_filial_vinculo_child_user_id'))

    op.drop_table('filial_vinculo')
    # ### end Alembic commands ###
