"""update planos/stripe

Revision ID: c0224b0c604d
Revises: fbdc6e0d19f1
Create Date: 2025-11-21 16:29:59.827031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0224b0c604d'
down_revision = 'fbdc6e0d19f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
