"""init

Revision ID: c09d9180e86b
Revises: 49f66aca9be7
Create Date: 2025-12-14 20:45:07.872094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09d9180e86b'
down_revision = '49f66aca9be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_switch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'location_id', name='uq_user_location')
    )
    op.create_index(op.f('ix_google_locations_user_id'), 'google_locations', ['user_id'], unique=False)
    op.add_column('review', sa.Column('google_location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_review_google_location_id'), 'review', ['google_location_id'], unique=False)
    op.create_foreign_key(None, 'review', 'google_locations', ['google_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_index(op.f('ix_review_google_location_id'), table_name='review')
    op.drop_column('review', 'google_location_id')
    op.drop_index(op.f('ix_google_locations_user_id'), table_name='google_locations')
    op.drop_table('google_locations')
    # ### end Alembic commands ###
