"""add consumido to retro payments

Revision ID: c4b82f83c966
Revises: c0224b0c604d
Create Date: 2025-11-23 13:12:38.206854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b82f83c966'
down_revision = 'c0224b0c604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('consumido', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'consumido')
    # ### end Alembic commands ###
