"""init

Revision ID: c752d9825bc5
Revises: 7b096e5e8884
Create Date: 2025-10-26 14:19:12.258795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c752d9825bc5'
down_revision = '7b096e5e8884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('location_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'location_name')
    # ### end Alembic commands ###
