"""Adiciona status e datas em FilialVinculo

Revision ID: cda6137fd232
Revises: bf8ecbe16e73
Create Date: 2025-08-12 22:40:24.314413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda6137fd232'
down_revision = 'bf8ecbe16e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='pendente'))
        batch_op.add_column(sa.Column('data_convite', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('data_aceite', sa.DateTime(timezone=True), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filial_vinculo', schema=None) as batch_op:
        batch_op.drop_column('data_aceite')
        batch_op.drop_column('data_convite')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
