"""Add campo plano_ate em UserSettings

Revision ID: deeef990cf96
Revises: 3896b73fecb0
Create Date: 2025-07-31 13:52:54.421305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deeef990cf96'
down_revision = '3896b73fecb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plano_ate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('plano_ate')

    # ### end Alembic commands ###
