"""init

Revision ID: ee59ff9feda9
Revises: 8798fae46b0b
Create Date: 2025-12-15 18:04:42.740885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee59ff9feda9'
down_revision = '8798fae46b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_locations', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('google_locations', sa.Column('manager_name', sa.String(length=255), nullable=True))
    op.add_column('google_locations', sa.Column('contact_info', sa.String(length=255), nullable=True))
    op.add_column('google_locations', sa.Column('default_greeting', sa.String(length=255), nullable=True))
    op.add_column('google_locations', sa.Column('default_closing', sa.String(length=255), nullable=True))
    op.add_column('google_locations', sa.Column('contexto_personalizado', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_locations', 'contexto_personalizado')
    op.drop_column('google_locations', 'default_closing')
    op.drop_column('google_locations', 'default_greeting')
    op.drop_column('google_locations', 'contact_info')
    op.drop_column('google_locations', 'manager_name')
    op.drop_column('google_locations', 'business_name')
    # ### end Alembic commands ###
