"""recria migration sincronizada

Revision ID: f16136067e50
Revises: ac045f16569a
Create Date: 2025-07-25 19:53:48.379182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16136067e50'
down_revision = 'ac045f16569a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consideracoes_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('data_uso', sa.Date(), nullable=False),
    sa.Column('quantidade_usos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consideracoes_uso')
    # ### end Alembic commands ###
