"""corrigindo review fk

Revision ID: f9a5961bd5ec
Revises: 7f091e6c4205
Create Date: 2025-12-17 18:59:47.432377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a5961bd5ec'
down_revision = '7f091e6c4205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
