"""init

Revision ID: fbdc6e0d19f1
Revises: bf0d42acfb3a
Create Date: 2025-11-21 14:06:04.554603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdc6e0d19f1'
down_revision = 'bf0d42acfb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('stripe_subscription_item_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'stripe_subscription_item_id')
    # ### end Alembic commands ###
